### ISSUE TITLE
Dotfiles Theft

### ISSUE THREAD

**Issue by alanmpitts** [davidlday/dotfiles#5]
Bro, I'm stealing some of your dotfile stuffs... ;-)

Lets get coffee sometime soon

**Comment by davidlday** [comment]
@alanmpitts - Steal away! I'll text or email you for coffee in the next day or two.

**Comment by alanmpitts** [comment]
Do ya think the coffee shops will close???? I've go a new gig btw

**Comment by davidlday** [comment]
@alanmpitts - Hey! Been a hot minute or two. You still in the area? Wanna meet up for coffee or lunch sometime in the next few weeks? Feel free to text me if you still have my number.

**Comment by alanmpitts** [comment]
That sounds great to me. Could you email me at alanmpitts@gmail.com? I'm flexible. The number I have for you ends in ***-***-*329‬. Is that still you?
